#!/bin/bash

UNBOUND_CONF="/etc/unbound/unbound.conf.d/pi-hole.conf"

# set num-threads for unbound matching the running machine
sed -i "s/num-threads: 1/num-threads: $(nproc)/" $UNBOUND_CONF
if [ "$USE_IPV6" == "true" ]; then
    sed -i "s/do-ip6: no/do-ip6: yes/" $UNBOUND_CONF
fi


echo "Starting unbound"

NAME="unbound"
DESC="DNS server"
DAEMON="/usr/sbin/unbound"
PIDFILE="/run/unbound.pid"

ANCHOR="/usr/sbin/unbound-anchor"

test -x $DAEMON || exit 0

# Override this variable by editing or creating /etc/default/unbound.
DAEMON_OPTS=""

$ANCHOR -v

$DAEMON -d $DAEMON_OPTS -c $UNBOUND_CONF
